# Generated by Django 3.1.14 on 2023-10-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('address', models.CharField(max_length=128, verbose_name='address')),
                ('shot_time', models.DateTimeField(verbose_name='shot_time')),
                ('file', models.FileField(default='picture_files/default.png', upload_to='picture_files', verbose_name='file')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
            ],
            options={
                'db_table': 'pictures',
            },
        ),
    ]
