# Generated by Django 4.2.6 on 2023-10-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picture_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="shot_time",
            field=models.DateTimeField(null=True, verbose_name="shot_time"),
        ),
    ]
